//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laba1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int ID_Student { get; set; }
        public string Surname { get; set; }
        public string Fistname { get; set; }
        public string MiddleName { get; set; }
        public int Group_ID { get; set; }
    
        public virtual Groups Groups { get; set; }
    }
}
